# Install a YAML language server in your IDE to validate against the schema, or use a tool
# like https://github.com/yaml-schema/yaml-schema
# yaml-language-server: $schema=./schedule-config-schema.yaml

- modules:
    - core/trino-main
    - [client/trino-jdbc, core/trino-spi, core/trino-web-ui, plugin/starburst-base-jdbc]
    - [
        plugin/trino-base-jdbc,
        plugin/trino-faker,
        plugin/trino-geospatial,
        plugin/trino-memory,
        plugin/trino-openlineage,
        plugin/trino-thrift,
      ]
    - [lib/trino-orc, lib/trino-parquet]
    - [
        lib/trino-filesystem,
        lib/trino-filesystem-azure,
        lib/trino-filesystem-alluxio,
        lib/trino-filesystem-cache-alluxio,
        lib/trino-filesystem-gcs,
        lib/trino-filesystem-manager,
        lib/trino-filesystem-s3,
        lib/trino-hdfs,
        lib/trino-hive-formats,
      ]
    - [
        plugin/starburst-warp-speed/starburst-warp-speed-core,
        plugin/starburst-warp-speed/starburst-warp-speed-extensions,
        plugin/starburst-warp-speed/starburst-warp-speed-plugin,
      ]
- modules:
    - [core/trino-main, plugin/trino-hive, testing/trino-tests]
  profiles:
    - gpu
  runners: [self-hosted, gha-fleet-ec2-1GPU-16CPU-64GB-amd64, latest]
  when:
    pushes: true
    labeled: [gpu]
- modules:
    - lib/trino-filesystem-azure
    - lib/trino-filesystem-gcs
    - lib/trino-filesystem-s3
    - plugin/trino-exchange-filesystem
    - starburst-buffer-service/starburst-buffer-data-server
  profiles:
    - cloud-tests
- modules:
    - lib/starburst-functions-client
    - plugin/starburst-functions
- modules:
    - plugin/starburst-objectstore
  profiles:
    - ""
    - hive-tests
  runners: [self-hosted, gha-fleet-ec2-8cpu-64gb-amd64, latest]
- modules:
    - plugin/starburst-objectstore
  profiles:
    - iceberg-delta
  runners: [self-hosted, gha-fleet-ec2-16cpu-64gb-amd64, latest]
- modules:
    - plugin/starburst-objectstore
  profiles:
    - cloud-tests
  runners: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
- modules:
    - plugin/trino-delta-lake
  runners: [self-hosted, gha-fleet-ec2-16cpu-64gb-amd64, latest]
- modules:
    - plugin/trino-delta-lake
  profiles:
    - cloud-tests
    - fte-tests
- modules:
    - starburst-buffer-service/starburst-buffer-exchange-tests
  profiles:
    - ""
    - test-buffer-exchange-failure-recovery
- modules:
    - plugin/trino-hive
  runners: [self-hosted, gha-fleet-ec2-16cpu-64gb-amd64, latest]
- modules:
    - plugin/trino-hive
  profiles:
    - cloud-tests
    - fte-tests
    - test-parquet
- modules:
    - plugin/trino-iceberg
  runners: [self-hosted, gha-fleet-ec2-16cpu-64gb-amd64, latest]
- modules:
    - plugin/trino-iceberg
  profiles:
    - cloud-tests
    - fte-tests
    - minio-and-avro
    # biglake-tests runs on nightly schedule only
- modules:
    - testing/trino-faulttolerant-tests
  profiles:
    - default
    - test-fault-tolerant-delta
    - test-fault-tolerant-hive
    - test-fault-tolerant-iceberg
- modules:
    - testing/trino-tests
  runners: [self-hosted, gha-fleet-ec2-16cpu-64gb-amd64, latest]
  matrix-properties:
    buildAll: true # buildAll is needed to build and package plugins required by TestConnectorSensitiveProperties
- modules:
    - plugin/trino-ignite
    - plugin/trino-postgresql
    - plugin/trino-redis
    - plugin/trino-resource-group-managers
## Nightly
- modules:
    - plugin/starburst-dynamodb
    - plugin/starburst-oracle
    - plugin/starburst-sap-hana
    - plugin/starburst-sqlserver
    - plugin/trino-elasticsearch
    - plugin/trino-kafka
    - plugin/trino-kudu
    - plugin/trino-mariadb
    - plugin/trino-mysql
    - plugin/trino-oracle
    - plugin/trino-sqlserver
  when:
    scheduled: nightly
- modules:
    - plugin/trino-iceberg
  profiles:
    - biglake-tests
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: nightly
    labeled: [iceberg:biglake]
- modules:
    - plugin/starburst-stargate
  runners: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
  when:
    scheduled: nightly
- modules:
    - plugin/starburst-stargate-parallel
  runners: [self-hosted, gha-fleet-ec2-4cpu-16gb-amd64, latest]
  when:
    scheduled: nightly
- modules:
    - plugin/trino-mongodb
  profiles:
    - ""
    - cloud-tests
  when:
    scheduled: nightly
- modules:
    - plugin/trino-pinot
  runners: [self-hosted, gha-fleet-ec2-8cpu-64gb-amd64, latest]
  when:
    scheduled: nightly
- modules:
      - plugin/trino-clickhouse
  runners: [self-hosted, gha-fleet-ec2-8cpu-64gb-amd64, latest]
  when:
    scheduled: nightly
- modules:
    - plugin/trino-bigquery
  profiles:
    - cloud-tests-1
    - cloud-tests-2
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: nightly
    labeled: [bigquery]
- modules:
    - plugin/trino-google-sheets
  profiles:
    - ""
    - cloud-tests
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: nightly
    labeled: [google-sheets]
- modules:
    - plugin/trino-redshift
  profiles:
    - ""
    - cloud-tests
    - fte-tests
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: nightly
    labeled: [redshift]
- modules:
    - plugin/starburst-salesforce
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: nightly
    labeled: [salesforce]
- modules:
    - plugin/starburst-snowflake
  profiles:
    - smoke-tests
  matrix-properties:
    cloud: amazon-web-service
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: nightly
    labeled: [snowflake]
## Weekly
- modules:
    - plugin/starburst-kdb
    - plugin/starburst-openapi
    - plugin/trino-hudi
    - plugin/trino-opensearch
    - plugin/trino-singlestore
    - plugin/trino-vertica
  when:
    scheduled: weekly
- modules:
    - plugin/starburst-snowflake
  profiles:
    - default
    # - smoke-tests  # smoke-tests on AWS run nightly
    - jdbc-integration-tests
    - parallel-integration-tests
    - fte-tests
  matrix-properties:
    cloud: amazon-web-service
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: weekly
    labeled: [snowflake]
    dispatches: false
# only run "default" and "smoke-tests" profile tests on Azure
- modules:
    - plugin/starburst-snowflake
  profiles:
    - default
    - smoke-tests
  matrix-properties:
    cloud: azure
  notify-channels:
    - C09HT9ETS73 # team-connectors-notify
  when:
    scheduled: weekly
    labeled: [snowflake]
    dispatches: false
## Only if impacted
- modules:
    - plugin/trino-cassandra
    - plugin/trino-druid
    - plugin/trino-duckdb
    - plugin/trino-exasol
  when:
    scheduled: never

