connector.name=warp_speed

hive.metastore=glue

hive.recursive-directories=true
hive.max-outstanding-splits=2000
hive.max-outstanding-splits-size=512MB
hive.max-split-size=64MB
hive.file-status-cache-expire-time=30m
hive.file-status-cache-tables=*
hive.allow-register-partition-procedure=true

fs.hadoop.enabled=false
fs.s3.enabled=true
fs.cache.enabled=true
fs.cache.directories=/opt/data/fsc
fs.cache.max-disk-usage-percentages=90
s3.path-style-access=true
http-rest-port=8085

warp-speed.proxied-connector=hive
warp-speed.config.is-single=false
node.environment=warp_speed
warp-speed.cluster-uuid=backendKey1
warp-speed.metrics.dump.interval=5s
warp-speed.use-http-server-port=false
warp-speed.config.extensions.enabled=true
warp-speed.config.http-rest-port-enabled=true
warp-speed.call-home.enable=false
warp-speed.store.path=file://varadaio-us-east1-systemtests/product-tests/multinode-warp-shared-glue/warp-2/
warp-speed.config.storage-temp-except.num-tries=3
warp-speed.import_export_s3_path=file://systemtest-export-import/test_export_import/pt
