connector.name=iceberg
iceberg.security=read_only
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=https://${ENV:DATABRICKS_HOST}/api/2.1/unity-catalog/iceberg-rest
iceberg.rest-catalog.warehouse=${ENV:DATABRICKS_UNITY_CATALOG_NAME}
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.token=${ENV:DATABRICKS_TOKEN}
iceberg.rest-catalog.vended-credentials-enabled=true
fs.s3.enabled=true
s3.region=${ENV:AWS_REGION}
