/*
 * Copyright Starburst Data, Inc. All rights reserved.
 *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF STARBURST DATA.
 * The copyright notice above does not evidence any
 * actual or intended publication of such source code.
 *
 * Redistribution of this material is strictly prohibited.
 */
package io.starburst.stargate.buffer.data.client;

public enum ErrorCode
{
    // OVERLOADED, // node is overloaded
    DRAINING, // node is draining (or drained)
    INTERNAL_ERROR, // general internal error
    EXCHANGE_FINISHED, // exchange still exists but already finished
    EXCHANGE_NOT_FOUND, // exchange not found
    EXCHANGE_CORRUPTED, // exchange in inconsistent state due to unexpected error when adding data pages
    CHUNK_NOT_FOUND, // chunk not found
    USER_ERROR, // unexpected input from the client
    BUFFER_NODE_NOT_FOUND, // generated by aggregated client when trying to access buffer node which is not part of the cluster
    DRAINING_ON_RETRY // node is DRAINING, which we learned on a retry call
}
