connector.name=postgresql
connection-url=${keystore:postgres_jdbc_url}
credential-provider.type=SECRETS
secrets-provider.name=keystore
secrets-provider.username-key=postgres_username
secrets-provider.password-key=postgres_password
