ALTER TABLE exact_match_source_selectors DROP PRIMARY KEY;
ALTER TABLE exact_match_source_selectors ADD id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY;
UPDATE exact_match_source_selectors SET id = ROWNUM;
ALTER TABLE exact_match_source_selectors ADD CONSTRAINT exact_match_source_selectors_pk PRIMARY KEY (id);
