cache-manager.name=warp_cache
warp-speed.enable.dictionary=true
node.environment=warp_speed_cache
warp-speed.config.is-single=false
warp-speed.metrics.dump.interval=5s

warp-speed.cluster-uuid=backendKey2
http-rest-port=8098
warp-speed.use-http-server-port=false
warp-speed.config.http-rest-port-enabled=true
warp-speed.config.extensions.enabled=true
warp-speed.call-home.enable=false
warp-speed.store.path=file://varadaio-us-east1-systemtests/product-tests/multinode-warp-glue-hive-cache/
