<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.trino</groupId>
        <artifactId>trino-root</artifactId>
        <version>481-e.0.16-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>starburst-warp-speed</artifactId>
    <packaging>pom</packaging>
    <description>Starburst Enterprise - Warp Speed</description>

    <modules>
        <module>starburst-warp-speed-core</module>
        <module>starburst-warp-speed-extensions</module>
        <module>starburst-warp-speed-plugin</module>
    </modules>

    <properties>
        <air.main.basedir>${project.parent.basedir}</air.main.basedir>
        <dep.lucene.version>10.4.0</dep.lucene.version>
        <dep.warp-speed-native.version>506</dep.warp-speed-native.version>
        <air.compiler.fail-warnings>true</air.compiler.fail-warnings>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>aopalliance</groupId>
                <artifactId>aopalliance</artifactId>
                <version>1.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.lucene</groupId>
                <artifactId>lucene-analysis-common</artifactId>
                <version>${dep.lucene.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.lucene</groupId>
                <artifactId>lucene-backward-codecs</artifactId>
                <version>${dep.lucene.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.lucene</groupId>
                <artifactId>lucene-core</artifactId>
                <version>${dep.lucene.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.21.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>1.1.1</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.6.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <configuration>
                        <!-- TODO should be handled by airbase when air.compiler.enable-preview=true (e.g. https://github.com/airlift/airbase/pull/404) -->
                        <additionalOptions>${jvm.enable-preview}</additionalOptions>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>errorprone-compiler</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <failOnWarning>true</failOnWarning>
                            <compilerArgs>
                                <arg>-XDcompilePolicy=simple</arg>
                                <arg>--should-stop=ifError=FLOW</arg>
                                <arg>
                                    -Xplugin:ErrorProne \
                                    -Xep:EqualsGetClass:OFF \
                                    -Xep:ArrayRecordComponent:OFF \
                                    <!-- Temporary disabled due to https://github.com/google/error-prone/issues/4598 -->
                                    -Xep:MissingOverride:OFF \
                                    -Xep:EnumOrdinal:OFF
                                </arg>
                            </compilerArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>
</project>
