/*
 * Copyright Starburst Data, Inc. All rights reserved.
 *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF STARBURST DATA.
 * The copyright notice above does not evidence any
 * actual or intended publication of such source code.
 *
 * Redistribution of this material is strictly prohibited.
 */
package com.starburstdata.trino.plugin.dynamodb;

import io.trino.testing.AbstractTestQueryFramework;
import io.trino.testing.QueryRunner;
import io.trino.tpch.TpchTable;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static com.google.common.collect.ImmutableSet.toImmutableSet;
import static com.google.common.io.MoreFiles.deleteRecursively;
import static io.trino.tpch.TpchTable.REGION;
import static java.util.Objects.requireNonNull;
import static org.assertj.core.api.Assertions.assertThat;

public class TestAutoGeneratedDynamoDbRsdSchema
        extends AbstractTestQueryFramework
{
    private static final String EXPECTED_AUTO_GENERATED_SCHEMAS_DIRECTORY = "src/test/resources/auto-generated-schemas";
    private static final List<TpchTable<?>> TPCH_TABLES = TpchTable.getTables();

    @TempDir
    private static Path actualSchemasDirectory;

    @Override
    protected QueryRunner createQueryRunner()
            throws Exception
    {
        TestingDynamoDbServer server = closeAfterClass(new TestingDynamoDbServer());
        return DynamoDbQueryRunner.builder()
                .setSchemaDirectory(actualSchemasDirectory)
                .setEndpointUrl(server.getEndpointUrl())
                .setAwsSecretKey("awsSecretKey")
                .setAwsAccessKey("awsAccessKey")
                .setFirstColumnAsPrimaryKeyEnabled(true)
                .setTables(TPCH_TABLES) // Explicitly defined the tables to make it reusable in the `testVerifyAutoGeneratedSchemas` test.
                .addConnectorProperties(
                        Map.of("dynamodb.generate-schema-files", "ON_START")) // Set to the same value as that of set in Galaxy configs.
                .build();
    }

    @Test
    public void testVerifyAutoGeneratedSchemas()
            throws IOException
    {
        requireNonNull(actualSchemasDirectory);
        assertThat(actualSchemasDirectory).exists();
        Set<String> expectedProgrammaticallyCreatedSchemas = TPCH_TABLES.stream().map(table -> table.getTableName() + ".rsd").collect(Collectors.toSet());
        Set<String> actualProgrammaticallyCreatedSchemas;
        try (Stream<Path> stream = Files.list(actualSchemasDirectory)) {
            actualProgrammaticallyCreatedSchemas = stream
                    .map(path -> path.getFileName().toString())
                    .collect(toImmutableSet());
        }

        assertThat(expectedProgrammaticallyCreatedSchemas).isEqualTo(actualProgrammaticallyCreatedSchemas);

        // Delete existing schemas
        deleteRecursively(actualSchemasDirectory);

        // Verify schema files do not exist
        assertThat(actualSchemasDirectory).doesNotExist();

        // Auto-recreate schemas
        assertQuerySucceeds("SHOW TABLES"); // rsd is auto generated as table is queried, if absent.

        for (TpchTable<?> table : TPCH_TABLES) {
            String tableName = table.getTableName();

            // Verify auto generated file content is as expected
            Path actualAutoGeneratedRsdFile = actualSchemasDirectory.resolve(tableName + ".rsd");
            Path expectedAutoGeneratedRsdFile1 = Path.of(EXPECTED_AUTO_GENERATED_SCHEMAS_DIRECTORY, tableName + "1.rsd");
            Path expectedAutoGeneratedRsdFile2 = Path.of(EXPECTED_AUTO_GENERATED_SCHEMAS_DIRECTORY, tableName + "2.rsd");

            if (table.getTableName().equals(REGION.getTableName())) {
                Path expectedAutoGeneratedRsdFile3 = Path.of(EXPECTED_AUTO_GENERATED_SCHEMAS_DIRECTORY, tableName + "3.rsd");
                assertThat(actualAutoGeneratedRsdFile).exists()
                        .satisfiesAnyOf(
                                actualFile -> assertThat(actualFile).hasSameTextualContentAs(expectedAutoGeneratedRsdFile1),
                                actualFile -> assertThat(actualFile).hasSameTextualContentAs(expectedAutoGeneratedRsdFile2),
                                actualFile -> assertThat(actualFile).hasSameTextualContentAs(expectedAutoGeneratedRsdFile3));
            }
            else {
                assertThat(actualAutoGeneratedRsdFile).exists()
                        .satisfiesAnyOf(
                                actualFile -> assertThat(actualFile).hasSameTextualContentAs(expectedAutoGeneratedRsdFile1),
                                actualFile -> assertThat(actualFile).hasSameTextualContentAs(expectedAutoGeneratedRsdFile2));
            }
        }
    }
}
