connector.name=delta_lake
hive.metastore=unity
hive.metastore.unity.host=${ENV:AZURE_DATABRICKS_HOST}
hive.metastore.unity.token=${ENV:AZURE_DATABRICKS_TOKEN}
hive.metastore.unity.catalog-name=${ENV:DATABRICKS_UNITY_CATALOG_NAME}
hive.metastore.unity.catalog-managed-table-enabled=true
hive.metastore.unity.vended-credentials-enabled=true
delta.security=allow-all
fs.azure.enabled=true
azure.auth-type=DEFAULT
delta.enable-non-concurrent-writes=true
