connector.name=hive
hive.metastore=unity
hive.metastore.unity.host=${ENV:DATABRICKS_HOST}
hive.metastore.unity.token=${ENV:DATABRICKS_TOKEN}
hive.metastore.unity.catalog-name=${ENV:DATABRICKS_UNITY_CATALOG_NAME}
hive.non-managed-table-writes-enabled=true
hive.metastore.unity.proxy.enabled=true
hive.metastore.unity.proxy.host=${ENV:PROXY_HOST}
hive.metastore.unity.proxy.port=${ENV:PROXY_PORT}
hive.metastore.unity.proxy.username=${ENV:PROXY_USERNAME}
hive.metastore.unity.proxy.password=${ENV:PROXY_PASSWORD}
hive.security=allow-all
hive.delta-lake-catalog-name=delta
fs.s3.enabled=true
# We need to give access to bucket owner (the AWS account integrated with Databricks), otherwise files won't be readable from Databricks
s3.canned-acl=BUCKET_OWNER_FULL_CONTROL
