name: Setup SCA
description: Setup for security's software composition analysis workflows.
inputs:
  aws-access-key-id:
    description: AWS access ID
  aws-secret-access-key:
    description: AWS secret ID
  secret-id:
    description: CodeArtifact secret

runs:
  using: composite
  steps:
    - name: CodeArtifact Login
      uses: ./.github/actions/starburst-setup
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        secret-id: ${{ inputs.secret-id }}
        login-maven: true
    - name: ECR Login
      shell: bash
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 843985043183.dkr.ecr.us-east-1.amazonaws.com
    - name: Setup Java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Maven Build
      shell: bash
      run: ./mvnw clean install -s .github/settings.xml -V -B --quiet -T 1C -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all
    - name: Don't Skip Deps
      # Endor will not be able to perform reachability analysis if this is set to true because "one or more of the declared dependencies is invalid"
      shell: bash
      run: ./mvnw versions:set-property -Dproperty=air.check.skip-dependency -DnewVersion=false -f core/trino-server/pom.xml --quiet
