name: on-ci-completion

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]

jobs:
  spot-loss-retry:
    runs-on: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: spot-loss-retry
        uses: actions/github-script@v8
        with:
          script: |
            console.log("Checking " + context.payload.workflow_run.html_url);
            const branch = context.payload.workflow_run.head_branch;
            const isMasterOrReleaseBranch = (branch == "master" || branch.startsWith("release-"));
            if (context.payload.workflow_run.run_attempt > 1) {
              console.log("Workflow was already rerun")
              return;
            }
            const jobs = await github.paginate(context.payload.workflow_run.jobs_url);
            let should_retry = false;
            jobs.filter(job => job.status == "completed" && job.conclusion == "failure").forEach(job => {
              console.log("Checking job " + job.name);
              let steps = Array();
              for (const step of job.steps) {
                steps.push(step);
              }
              if (steps.length < 2) {
                console.log("Not enough steps for job: " + job.name);
                return;
              }
              const lastStep = steps[steps.length - 1];
              // If failure happened due to spot loss, last step will not be "Complete job".
              // "Complete job" appears only if job ended in somewhat expected way
              if (lastStep.name == "Complete job") {
                console.log("Last step name: " + lastStep.name + " => Probably not a spot loss");
                return;
              }
              if (lastStep.conclusion != "skipped") {
                console.log("Last step: " + lastStep.name + " concluded with: " + lastStep.conclusion + " => Probably not a spot loss");
                return;
              }
              console.log("Will trigger rerun-failed-jobs due to job: " + job.name);
              should_retry = true;
              return;
            });
            if (isMasterOrReleaseBranch) {
              console.log("Will trigger rerun-failed-jobs once for release branch: " + branch);
              should_retry = true;
            }
            if (should_retry) {
              await github.request("POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs", {
                owner: context.payload.workflow_run.repository.owner.login,
                repo: context.payload.workflow_run.repository.name,
                run_id: context.payload.workflow_run.id
              });
            }
