connector.name=hive
hive.metastore=unity
hive.metastore.unity.host=${ENV:GCS_DATABRICKS_HOST}
hive.metastore.unity.token=${ENV:GCS_DATABRICKS_TOKEN}
hive.metastore.unity.catalog-name=${ENV:DATABRICKS_UNITY_CATALOG_NAME}
hive.non-managed-table-writes-enabled=true
hive.security=allow-all
hive.delta-lake-catalog-name=delta
fs.hadoop.enabled=false
fs.gcs.enabled=true
